### ISSUE TITLE
Library doesn't work without of laravel

### ISSUE THREAD

**Issue by Awilum** [5am-code/laravel-notion-api#79]
I am trying to use this library without laravel, but seems its doesn't suppose to work.

php
```php
use FiveamCode\LaravelNotionApi\Notion;

$notion = new Notion('');
```

Error:
```
Fatal error: Uncaught RuntimeException: A facade root has not been set. in /Applications/MAMP/htdocs/projects/flextype/flextype/project/plugins/notion/vendor/illuminate/support/Facades/Facade.php:335 Stack trace: #0 /Applications/MAMP/htdocs/projects/flextype/flextype/project/plugins/notion/vendor/fiveam-code/laravel-notion-api/src/Notion.php(72): Illuminate\Support\Facades\Facade::__callStatic('withHeaders', Array) #1 /Applications/MAMP/htdocs/projects/flextype/flextype/project/plugins/notion/vendor/fiveam-code/laravel-notion-api/src/Notion.php(62): FiveamCode\LaravelNotionApi\Notion->connect() #2 /Applications/MAMP/htdocs/projects/flextype/flextype/project/plugins/notion/plugin.php(29): FiveamCode\LaravelNotionApi\Notion->__construct('') #3 /Applications/MAMP/htdocs/projects/flextype/flextype/src/flextype/core/Plugins.php(423): require_once('/Applications/M...') #4 /Applications/MAMP/htdocs/projects/flextype/flextype/src/flextype/core/Plugins.php(191): Flextype\Plugins->includeEnabledPlugins() #5 /Applications/MAMP/htdocs/projects/flextype/flextype/src/flextype/core/Plugins.php(51): Flextype\Plugins->init() #6 /Applications/MAMP/htdocs/projects/flextype/flextype/src/flextype/flextype.php(350): Flextype\Plugins->__construct() #7 /Applications/MAMP/htdocs/projects/flextype/flextype/index.php(46): require_once('/Applications/M...') #8 {main} thrown in /Applications/MAMP/htdocs/projects/flextype/flextype/project/plugins/notion/vendor/illuminate/support/Facades/Facade.php on line 335
```

any ideas how to fix this ?

**Comment by johguentner** [comment]
Hey @Awilum,
thank you for your question. 
This library is intended to be used with Laravel, since it is based partially on its structure and depends on certain libraries. 
Since this is something which won't be changed in the near future, I'm closing this issue.
